import { env } from '../env.mjs';

export const siteConfig = {
	title: 'Sobha Townpark – NYC-Themed Luxury Residences in Bengaluru',
	description:
		"Experience luxury living at Sobha Townpark, Bengaluru's premier NYC-themed township offering modern residences with world-class amenities.",
	keywords: () => [
		'Sobha Town Park',
		'Sobha Town Park Bengaluru',
		'Sobha Town Park Bangalore',
		'Sobha Town Park Hosur',
		'Sobha Town Park Homes',
		'Sobha Town Park Apartments',
		'Sobha Town Park Flats',
		'Sobha Town Park Villas',
		'Sobha Town Park Price',
		'Sobha Town Park Cost',
		'Sobha Town Park Location',
		'Sobha Town Park Reviews',
		'Sobha Town Park Floor Plan',
		'Sobha Town Park Master Plan',
		'Sobha Town Park RERA',
		'Sobha Town Park Brochure',
		'Sobha Town Park Possession Date',
		'Sobha Town Park New York Themed Township',
		'Sobha Town Park Electronic City',
		'Luxury Apartments in Hosur Road',
		'Premium Homes in Bangalore',
		'Best Residential Projects in Bengaluru',
		'Upcoming Residential Projects in Bangalore',
		'New Launch Sobha Town Park',
		'Sobha Town Park Booking',
		'Sobha Town Park 2 BHK Apartments',
		'Sobha Town Park 3 BHK Apartments',
		'Sobha Town Park 4 BHK Apartments',
		'Sobha Town Park Investment Opportunity',
		'Sobha Town Park Gated Community',
		'Luxury Living in Bangalore',
		'Sobha Town Park Amenities',
		'Sobha Town Park Connectivity',
		'Sobha Town Park Payment Plan',
		'Sobha Town Park Pre-launch Price',
		'Sobha Town Park Completion Date',
		'Sobha Town Park Resale',
		'Sobha Town Park Under Construction',
		'Sobha Town Park Near Electronic City',
		'RERA Approved Projects in Bengaluru',
		'Top Real Estate Projects in Bangalore',
		'Best Flats for Sale in Bengaluru',
		'Luxury Homes Near IT Hub Bangalore',
		'Sobha Town Park Contact Number',
		'Sobha Town Park Site Visit',
		'Sobha Town Park Rental Potential',
		'Sobha Town Park Investment Benefits',
		'Sobha Town Park Infrastructure',
	],
	url: () => env.APP_URL,
	// googleSiteVerificationId: () => env.GOOGLE_SITE_VERIFICATION_ID || '',
};
