import { env } from '../env.mjs';

export const siteConfig = {
	title: 'Sobha Magnum – Luxury Residences in Bengaluru',
	description:
		"Experience luxury living at Sobha & Magnum, Bengaluru's premier township offering modern residences with world-class amenities.",
	keywords: () => [
		'Sobha Magnum',
		'Sobha Magnum Bengaluru',
		'Sobha Magnum Bangalore',
		'Sobha Magnum Hosur',
		'Sobha Magnum Homes',
		'Sobha Magnum Apartments',
		'Sobha Magnum Flats',
		'Sobha Magnum Villas',
		'Sobha Magnum Price',
		'Sobha Magnum Cost',
		'Sobha Magnum Location',
		'Sobha Magnum Reviews',
		'Sobha Magnum Floor Plan',
		'Sobha Magnum Master Plan',
		'Sobha Magnum RERA',
		'Sobha Magnum Brochure',
		'Sobha Magnum Possession Date',
		'Sobha Magnum Township',
		'Sobha Magnum Electronic City',
		'Luxury Apartments in Hosur Road',
		'Premium Homes in Bangalore',
		'Best Residential Projects in Bengaluru',
		'Upcoming Residential Projects in Bangalore',
		'New Launch Sobha Magnum',
		'Sobha Magnum Booking',
		'Sobha Magnum 2 BHK Apartments',
		'Sobha Magnum 3 BHK Apartments',
		'Sobha Magnum 4 BHK Apartments',
		'Sobha Magnum Investment Opportunity',
		'Sobha Magnum Gated Community',
		'Luxury Living in Bangalore',
		'Sobha Magnum Amenities',
		'Sobha Magnum Connectivity',
		'Sobha Magnum Payment Plan',
		'Sobha Magnum Pre-launch Price',
		'Sobha Magnum Completion Date',
		'Sobha Magnum Resale',
		'Sobha Magnum Under Construction',
		'Sobha Magnum Near Electronic City',
		'RERA Approved Projects in Bengaluru',
		'Top Real Estate Projects in Bangalore',
		'Best Flats for Sale in Bengaluru',
		'Luxury Homes Near IT Hub Bangalore',
		'Sobha Magnum Contact Number',
		'Sobha Magnum Site Visit',
		'Sobha Magnum Rental Potential',
		'Sobha Magnum Investment Benefits',
		'Sobha Magnum Infrastructure',
	],
	url: () => env.APP_URL,
	// googleSiteVerificationId: () => env.GOOGLE_SITE_VERIFICATION_ID || '',
};
